### ISSUE TITLE
Getting workers to run

### ISSUE THREAD

**Issue by Eforen** [Ni55aN/D3-Node-Engine#1]
I can't seem to get the workers to run even in the sample step you give on codepen... what am I missing here...

**Comment by Ni55aN** [comment]
For which platform do you compile?  Have you tried [this example](https://github.com/Ni55aN/D3NE-engine/blob/master/example)?

**Comment by Eforen** [comment]
@Ni55aN you can see my exact code here https://github.com/Eforen/FlowHS as it is an open source project I am building into Electron for Windows 10 I believe it runs on chromium

If you do download the code and spin it up the the shortcuts you need to know if you don't are 

Shortcut | Action
------------ | -------------
Ctrl+Shift+R | reload the page
Ctrl+Shift+i | open chrome inspector

Also files of interest are

Filename|Relevance 
------------ | -------------
app/editor.html|The actual HTML f the editor window
process/js/editor.js|The place where all the relevant JS is that is linked in the HTML page

# Debugging
I have confirmed with brakepoints that ```engine.process()``` is called originally I did not pass anything into process the simulation does not need any external code input.

I could just not understand what ```engine.process()``` actually does

I have confirmed via breakpoints that when you click a checkbox it does call the waiting function which changes the data but not sure why the worker never gets called.

# Alternate Resolution
I guess I could mirror the node structure in my own data framework and then just listen for disconnect and connect events and such using D3NE as just an editor not part of the actual logic simulation framework directly. Infact that may be a better idea in the long run but I wanted to give it a try to see what is better for this project.

**Comment by Ni55aN** [comment]
@Eforen `process()` must accept JSON data from editor. Log:

![2017-11-24_230116](https://user-images.githubusercontent.com/8259641/33223797-d7e744d0-d16b-11e7-8897-8846b680379e.png)

So you need replace
```js
 engine.process(1,null);
```
to
```js
  engine.process(editor.toJSON(),null); 
```

![2017-11-24_230211](https://user-images.githubusercontent.com/8259641/33223799-dc291f14-d16b-11e7-907e-245f2d37a6b6.png)

**Comment by Ni55aN** [comment]
And one more thing, this repository is intended only for solving problems with C ++ implementation of the engine

**Comment by Eforen** [comment]
oops I didn't notice I was in the C++ version sorry >.< its good to know that that is what process expects but I ended up just layering a set of extensions on top of D3NE if something changes at a source the change propagates down the tree until something does not change because of what I am designing I think that will work much better then updating everything in the tree thank you for your help though! that change does make it work
